### ISSUE TITLE
Minecraft Version 1.10.2

### ISSUE THREAD

**Issue by EpiXSim0n** [michaelzangl/minebot#123]
Is it currently possible to run minebot with Minercaft version 1.10.2?
For me it is not possible to run minebot at version 1.10.2.
Any solutions?
Help pls.

**Comment by michaelzangl** [comment]
No.

You can port it if you want to.

**Comment by EpiXSim0n** [comment]
So this mod is not supported longer?
And wont be updated anymore?
:/

**Comment by michaelzangl** [comment]
I don't have the time to update it, due to other projects I'm working on. If you want to, feel free to create a pull request.

**Comment by EpiXSim0n** [comment]
I would. If I would have the knowledge...
But so it is like it is :/
I would be very happy if you find some time in future to update this awesome projekt =)

**Comment by kkprince1998** [comment]
I would love to port it as well, however my attempts are not working that we'll. Where did you get the forge ap information?
