### ISSUE TITLE
MineBot.properties

### ISSUE THREAD

**Issue by BamBam042** [michaelzangl/minebot#124]
Hello , 

Sorry for my bad english , i try my best :+1: 

The file " minebot.properties " no longer appears compared to the old version , or it comes from ?

Great job , you are really very strong! :100: 
GoodDay :)

**Comment by michaelzangl** [comment]
File was renamed to minebot.josm.

Use `/minebot settings edit`

**Comment by BamBam042** [comment]
Hello , 

[Minebot] Could not open the file

/:
