### ISSUE TITLE
"/minebot store" Doesn't work! - 1.8.2

### ISSUE THREAD

**Issue by Lucasxp32** [michaelzangl/minebot#125]
I'm using Forge 11.14.1.1334 with other mods
I'm using the lastest release: v0.4b4
I've tried everything: the frames into the chests, the frames ON the chests by a glitch (I put the frames in a block, then I replace it quickly by the chest).

I'll try to download the old versions to see if it works, maybe other mods are messing with this function.

**Comment by walaoaaa1234** [comment]
try shift-right click at chests when holding frame, and put a item you want to store inside frame.
