### ISSUE TITLE
An another strategy took over

### ISSUE THREAD

**Issue by Hury999** [michaelzangl/minebot#128]
When I harvest sugar cane farm this happens every time after 15 seconds of harvesting.. How I can prevent this?
I created Script but it doesn't help :

repeat:
/minebot plant sugar_cane
/minebot pause 10

**Comment by michaelzangl** [comment]
What other strategy took over? What do you see in the upper right corner of the screen?

**Comment by Hury999** [comment]
Nah, it's okay now.. Something was wrong with timer now it's fine..
