### ISSUE TITLE
Where ic can find minebot 1.8.9

### ISSUE THREAD

**Issue by merosoko** [michaelzangl/minebot#131]
https://github.com/michaelzangl/minebot/releases here only 1.8 releases :(
sorry for stupid question
Where i can find minebot 1.8.9*

**Comment by michaelzangl** [comment]
You have to compile it yourself from the source.

**Comment by merosoko** [comment]
And the last stupid question where i can find the sourse? :)

**Comment by merosoko** [comment]
ok, i find it, but when i am trying to compiling minebot for 1.8.9, \minebot-forge-1.8.9\releases is empty
