### ISSUE TITLE
Recipes question

### ISSUE THREAD

**Issue by merosoko** [michaelzangl/minebot#136]
How can I add custom recipes to /minebot craft ?

**Comment by michaelzangl** [comment]
Which recipe would you like to add?

The bot uses the default minecraft recipes available (expect for some special recipes it does not understand). This is why you cannot add your own.

**Comment by merosoko** [comment]
I would like to use recipes from server plugin's. Many of the recipes are changed, they craft from vanilla items but a different recipe. whether there is some sort of a file that stores all the recipes? I could change them. =)

**Comment by michaelzangl** [comment]
No. The bot is only designed to work with vanilla minecraft and takes the recipes directly from the minecraft source.
