### ISSUE TITLE
Update to 1.11

### ISSUE THREAD

**Issue by polkovnikov-ph** [michaelzangl/minebot#142]
Needs an update to 1.11

**Comment by mathis9520** [comment]
You do not want or you can't ?

**Comment by michaelzangl** [comment]
I don't have time for it. I have some other work to do and don't really have time for Minecraft.

**Comment by mathis9520** [comment]
I really want to help you, but i don't know how to program and code. So if it's just replacing IDs or this kind of things i can do, but if it's very diffuclt i can't ;'(

**Comment by polkovnikov-ph** [comment]
@mathis9520 No, it's not simple at all.

**Comment by michaelzangl** [comment]
It would take about one week for an experienced developer...

**Comment by biolibi** [comment]
but do you think you will have time one day or this project is dead?

**Comment by ali6836** [comment]
Say I were to want to update this to 1.9, what would I need to do in order to get it working?

**Comment by JakeN9** [comment]
I could try updating it, if anyone else would like to help it would be greatly appreciated.

**Comment by JakeN9** [comment]
This is an amazing project and it deserves updating.

**Comment by eileen12** [comment]
I am working on a similar project. I call it BotAPI.

On 11-Jun-2017 3:35 PM, "JakeN9" <notifications@github.com> wrote:

This is an amazing project and it deserves updating.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/michaelzangl/minebot/issues/142#issuecomment-307618383>,
or mute the thread

**Comment by michaelzangl** [comment]
See branch `forge-1.11`

**Comment by reverofevil** [comment]
Great!

**Comment by Eyremba** [comment]
Dude are you fucking kidding us? Update it as fast as possible @michaelzangl !!!!

**Comment by JakeN9** [comment]
@Eyremba I hope you're kidding, he works on this project in his free time and hes not obliged to do anything!

**Comment by Eyremba** [comment]
@JakeN9 I hope that you are kidding!!! He did NOT update AimBow for more than 2 years now!!

**Comment by JakeN9** [comment]
Sorry why has jsma https://github.com/Eyremba/jsmaz not been updated since **FOR 6 WHOLE YEARS!!**

**Comment by JakeN9** [comment]
>:(

**Comment by polkovnikov-ph** [comment]
@Eyremba @JakeN9 Could you please keep this discussion civilized and on-topic?
