### ISSUE TITLE
Online servers can read /minebot commands?

### ISSUE THREAD

**Issue by trevorwood1993** [michaelzangl/minebot#144]
Really love this mod, but it looks like online servers can read the /minebot commands
http://gaming.stackexchange.com/questions/298328/can-online-servers-read-my-minecraft-commands

Is there anyway to get around this? Even something like changing /minebot to /mb or /skipper would be enough to at least talk your way out of it if you were caught.

Also, I play a modded version of minecraft (LOTR mod by Mevans) 
Is there anyway to add ores to mine?

**Comment by michaelzangl** [comment]
> Is there anyway to get around this?

Not everything someone writes on stackexchange is correct ;-).

Minebot commands are never sent to the server. Magic ;-). This is also true for tab complete in 1.8, but tab complete does not show up in server logs.

**Comment by trevorwood1993** [comment]
You're a genius man. Thank you so much.
