### ISSUE TITLE
The path jars

### ISSUE THREAD

**Issue by ChickenPillow** [michaelzangl/minebot#154]
I'm trying to upgrade the minebot mod to 1.11.2. Previously I have only worked with spigot/bukkit _plugins_ for minecraft (using eclipse). First is there any main differences between how to make a mod and plugin (apart from the code and the different path jars)? and second will I need to download all of the new jars (so that they are 1.11.2 compatible) to build the path? Could you give a link to all the jar downloads?

Thanks

**Comment by opticyclic** [comment]
FYI: There are a couple of forks that are working on this too
E.g https://github.com/rakslice/minebot/commits/1_11_port_before_changes

You shouldn't have to download jars explicitly.
You need to update the dependencies in build.gradle and the build process will pull them in.

**Comment by michaelzangl** [comment]
Updating gradle is the easiest part. If you are unsure, start a new forge mod and compare the build.gradle. After adjusting the build.gradle, you can simply do a `./gradlew build` (Linux) ;-)

Updating the bot code is the hard part.
