### ISSUE TITLE
Reformat To A Longer Line Length For Readability

### ISSUE THREAD

**Issue by opticyclic** [michaelzangl/minebot#157]
In certain parts of the code the line wrapping makes it difficult to read.

A perfect example is [this](https://github.com/michaelzangl/minebot/blob/af4ade5582b7068bc97e7a31cd8d8298532dbf7e/Minebot/src/net/famzangl/minecraft/minebot/ai/task/AITask.java#L38-L39)

	protected static final Logger LOGGER = LogManager
			.getLogger(AITask.class);

That would be much easier to read if it was one line so your eyes don't have to scan back and forth

	protected static final Logger LOGGER = LogManager.getLogger(AITask.class); 

[Back in 2011](http://blog.vogella.com/2011/09/06/eclipse-default-line-length-of-80-chars-outdate/) people were already discussing that the 80 char limit was outdated in eclipse. The consensus there was for 120 chars.

[Intellij IDEA](http://stackoverflow.com/a/29751140) also defaults to 120 chars.

Google take a slightly more conservative approach at [100 chars.](https://google.github.io/styleguide/javaguide.html#s4.4-column-limit)

Can we check in a code style (maybe a CheckStyle xml so that it works independent of IDE) that specifies a slightly longer line length and then reformat the code?

**Comment by michaelzangl** [comment]
You can use any line length you like - I simply used the eclipse default of 80 chars. It makes development easier when having multiple files open side to side on one screen, so it has it's pros and cons ;-)

**Comment by opticyclic** [comment]
OK. Fair enough I just wanted to throw it out there as an option.
