### ISSUE TITLE
One Letter Variable Names Make The Code Hard to Read

### ISSUE THREAD

**Issue by opticyclic** [michaelzangl/minebot#158]
Unless the variable is a co-ordinate (x, y, z) or an iterator in a for loop (i), having one letter variable names makes the code hard to read unless you are intimate with all of it.

This is a placeholder for a pull request.

**Comment by michaelzangl** [comment]
Closed with #159

If you add a "fixes #158" in the commit / PR, Github will close this automatically.

You don't need placeholders for PRs ;-)
