### ISSUE TITLE
minebot Building Function

### ISSUE THREAD

**Issue by iToasters** [michaelzangl/minebot#160]
When I make a insertnamehere.buildscript.txt file it says the blocks are "#Missing". I am using the /minebuild reverse command. How do I fix this issue? (I'm trying to make it build me a cactus farm but its saying all the cactus is missing.)

Edit: It looks like cactus isn't a block that is valid to run with /minebuild :(
https://gyazo.com/5367738c57a3f0aad815a1d54a8e626a
@michaelzangl 
~iToasters

**Comment by michaelzangl** [comment]
Cactus is not supported at the moment (the bot just stays away from them, so it cannot place them using the current placement methods)
