### ISSUE TITLE
Which files are needed for the mining aspect of this project?

### ISSUE THREAD

**Issue by ali6836** [michaelzangl/minebot#163]
I wish to attempt to update minebot, but only for the mining feature. Which files do I need for the mining aspect of this mod.

**Comment by michaelzangl** [comment]
Most of them.

Minebot works using strategies. The strategies are quite universal. Once you get mining working, lumberjack and most other features will work as well automatically, since they use the same data structures.

**Comment by ali6836** [comment]
When you say most of them, does that also include all of the net.famzangl.minecraft.minebot.build files or not? I'm quite new to coding, and have gotten rid of 300 of the 1000+ errors.

**Comment by michaelzangl** [comment]
No, the .build files are not required. They don't contain much minecraft-version-dependent stuff (at least not the one that could not be changed using a simple search+replace). Map is not needed as well.

The most important part is in the .ai package. But this is the biggest one. Do not only search for compile errors - you need to adjust the reflective calls, too.

You might be able to remove/fake the net handler and play without it.
