### ISSUE TITLE
How to clear out an area / set coordinates?

### ISSUE THREAD

**Issue by Cubital** [michaelzangl/minebot#165]
Is there any more complete site that tells you how to use each command and what they do? Like an API of sorts? And I don't mean the /help command... but I mean some way to get a descripition of what everything does..

Thanks in advance,
Cubital

**Comment by walaoaaa1234** [comment]
@Cubital wiki? https://github.com/michaelzangl/minebot/wiki

**Comment by couldbejake** [comment]
Hey there. You can do the following commands to clear out an area.

/minebuild pos1 ~ ~ ~
/minbuild pos2 ~ ~ ~
/minebuild clear

Stand in the positions for pos1 or pos2, or use relative or exact positions.

**Comment by JakeN9** [comment]
Also if i were you i'd look at the previous 0.2 and 0.3 versions of MineBot which contain way more information.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1446167-minebot-a-bot-that-plays-minecraft-for-you-mining

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2283099-minebot-0-3-released-can-now-store-in-chests-craft
