### ISSUE TITLE
Someone compile new version of minebot?

### ISSUE THREAD

**Issue by Hury999** [michaelzangl/minebot#168]
So every time i want to compile it has problems.
Maybe cuz i'm on windows? In readme says it must be linux..

**Comment by michaelzangl** [comment]
Please provide a detailed error description.

It is best to use Linux. You can use Windows, too. Open a terminal (command prompt) in the Minebot directory, then run:
```
gradlew.bat build
```
It will create the minebot mod file in `build/libs`

I'm compiling new versions as soon as they are stable enough.
