### ISSUE TITLE
mining doesn't work

### ISSUE THREAD

**Issue by TheTechPony** [michaelzangl/minebot#172]
I know you just released the pre-release but I don't know what bugs you do and don't know about. /minebuild clear was working fine until I tried /minebot lumberjack and now it crashes whenever I try anything with digging involved

**Comment by TheTechPony** [comment]
https://pastebin.com/EitFijCY

**Comment by michaelzangl** [comment]
It might be better now. This seems to be a problem with the translation that forge does.

**Comment by ghost** [comment]
How do I install the updated version that doesn't crash?

**Comment by Hury999** [comment]
Compile it but plant doesn't work even in updated version so...

**Comment by michaelzangl** [comment]
I did a new release (1.12.1) - if it still crashes, send a bug report.
