### ISSUE TITLE
/minebot plant not working properly 1.12

### ISSUE THREAD

**Issue by creeperofthnight** [michaelzangl/minebot#174]
When attempting to use /minebot plant, the bot is able to harvest wheat seemingly fine. The issue appears to happen once it has seeds in hand and attempts to plant. It plants the first seed, and immediately freezes until I cancel.  Also seem to have a similar issue with sugar cane. He can harvest just fine, but if he attempts to plant sugar cane, I get the message :Cannot select sugar_cane (83) 

Not sure if you are aware or even will attempt to fix these, but I appreciate all that you put into this amazing bot.

**Comment by Hury999** [comment]
I have same issue..

**Comment by ghost** [comment]
Same here. Plants first Carrot and doesnt move on to the next block....

**Comment by michaelzangl** [comment]
Fixed in v1.12.2
