### ISSUE TITLE
Commands doesn't works

### ISSUE THREAD

**Issue by Hury999** [michaelzangl/minebot#175]
So sometime "**/minebot mine**" and "**/minebot plant**" doesn't work, white text of what to do things just disappear after I type command..

I hope you will fix these bugs with these commands, cuz they are often used..

Here is video:
https://vimeo.com/224957956

**Comment by couldbejake** [comment]
Hi, It looks to me like when you're asking minebot to mine it hasn't properly cleared out it's previous task, in order to do this, I recommend doing.
`/minebuild reset - Reset the build queue && Undos all scheduled tasks`
before doing
`/minebot mine`

**Comment by michaelzangl** [comment]
Reset _should_ not have anything to do with it.

At first I thought it would have something to do with the starting position, but they should be finde. Is this happening after a restart, too?

The bot will refuse to work if creepers are nearby (currently without error message). But in your case this should not be a problem.

Does a restart of the client fix it? Do you have any idea of strange things that happened before that that could have led to this? In your Minecraft launcher, you have the option to enable console output. The launcher needs to stay open for this. You can then see a log of what Minecraft did (you can also find this in the minecraft directory, I think).

**Comment by Hury999** [comment]
Okay I recorded console output and it displayed something when I type command. Have look at it. It would be nice if you could  fix this also **/minebot plant** command doesn't work, after it plants once it start to lag (huge FPS drop and not moving).

Video:
https://vimeo.com/225086825

**Comment by michaelzangl** [comment]
The log says that "Path finder could not find a path". Since it decides this so quickly, I think that the pathfinder has a problem with your starting position. But I don't know what problem it has.

I could not reproduce it yet.

**Comment by Hury999** [comment]
I think It's up to the server, cuz on other server I don't have any problem except form plant command which doesn't work(mentioned)..

**Comment by michaelzangl** [comment]
Fixed starting block lists / side blocks in 1.15
