### ISSUE TITLE
take from chests and sell (/minebot get)

### ISSUE THREAD

**Issue by Cannuner** [michaelzangl/minebot#189]
i see in the older minebot (1.7) [http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2283099-minebot-0-3-released-can-now-store-in-chests-craft?page=2](url) it was able to take specific items from chests, well thats great but it isn't supported in the 1.8 forge mod? that'd be great if it was, please let me know if im just missing it. I've read the /minebot help several times and did some research, thanks!

**Comment by michaelzangl** [comment]
I fixed it yesterday but have not pushed the changes yet (still some bugs)

https://github.com/michaelzangl/minebot/wiki/Inventory-and-crafting

**Comment by michaelzangl** [comment]
Fixed in v1.12.2
