### ISSUE TITLE
/minebot pathfind does cannot jump sideways up

### ISSUE THREAD

**Issue by ghost** [michaelzangl/minebot#192]
The command /minebot pathfind das not work.
When I type in /minebot pathfind 439 66 -655
The script text at the right corner appeaers shortly and then the scipt stops.

**Comment by ghost** [comment]
Found The Problem... 
Blocks which are not a Cube do not work.

**Comment by creeperofthnight** [comment]
What do you mean by not a cube? I have the same issue you had in the first post. How do you properly enter the coordinates?

**Comment by ghost** [comment]
It has nothing to do with coords.
The following is the Problem but its no big Problem if you know how to fix it.
If the whole field is planted the Bot cant get out if it.
![inked2017-07-25_09 03 00_li](https://user-images.githubusercontent.com/16577384/28560142-cbff0a8e-7119-11e7-83b5-3b360bef7c9d.jpg)

To fix this i did this:
![inked2017-07-25_09 03 48_li](https://user-images.githubusercontent.com/16577384/28560178-f298af42-7119-11e7-887c-bd9667d0dd98.jpg)
Instead of The Grassblock Cobble would be better cause the bot will plant seeds (minebot plant) on the dirt an then its stuck again.

It also works if only one Grassblock is unplanted:
![inked2017-07-25_09 04 14_li](https://user-images.githubusercontent.com/16577384/28560272-471fed14-711a-11e7-889d-0d2769bedcdc.jpg)

So the Problem i think are not the Farmland blocks that are not a Cube they are a little lower than normal blocks.
The Problem is when the whole field is planted and the bot thinks it cant step into weed,carrot or potatoes whatever is planted....
And then /minebot pathfind aborts....
The rest of /minebot pathfind works without bugs for me i had no Problem with coordinates and co....
The only thing i found  is that if the destination is more than 40-60 Blocks away the Bot also aborts, but i fixed this with intermediates points eg.
/minebot pathfind -620 60 450 
/minebot pathfind -620 60 480
/minebot pathfind -620 60 520  
/minebot pathfind -620 60 570
Instead of directly typing in /minebot pathfind -620 60 570 


ALL TESTED IN MULTIPLAYER!
PS: I know my photoshops skills are awesome! 



 

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by creeperofthnight** [comment]
Thanks for the clarification, I was always trying to pathfind coords that were too far away. Should have been obvious, can't pathfind chunks you haven't loaded! I like your incremental approach.

**Comment by michaelzangl** [comment]
The bot was told to not jump down on planted blocks while planting (it does not differentiate between 0.5 high and 1 high source blocks there).

When moving up, the bot basically searches a way where it could build it's way up. To jump insead of place a block is a path optimization done later. This is why the bot can only jump up from a source that is empty (air) and has solid ground below it.

**Comment by ghost** [comment]
Its no big deal. So i think this has time to fix.
can you take a look at 50b23630e587c820b3c69fd6b0067064ef5b264a
Cant wait for fishing :P

**Comment by Sopitive** [comment]
I am having trouble with this command too. The bot won't pathfind even though the block I'm sending it to is an actual block that it can stand on.

**Comment by ghost** [comment]
What block type is it and how far away?

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Sopitive** [comment]
They are full blocks and after a little testing, the minebot doesn't seem to be able to pathfind more than 83 blocks away from its current location. Any coordinates higher than that ammount of blocks away and the minebot will not pathfind.

**Comment by michaelzangl** [comment]
Both issues (pathfinder range limitation + jump up from planted area) are fixed in 1.15.2b1
