### ISSUE TITLE
Server has anti-xray how to avoid? 

### ISSUE THREAD

**Issue by SlevinShadow** [michaelzangl/minebot#195]
Its going for the ores that the anti-xray is putting their and making it waste pickaxes and time. any help?

**Comment by ghost** [comment]
Try /minebot mine orebfuscated

**Comment by michaelzangl** [comment]
Best is to stack `/minebot mine nearby` and `/minebot tunnel`, see examples for scripts

**Comment by purpshell** [comment]
micheal question, how to exray to diamonds only?

**Comment by michaelzangl** [comment]
/minebot settings edit

In this file, you can set the priority of the different ores or remove the ones you don't want to be mined.

https://github.com/michaelzangl/minebot/wiki/Settings
