### ISSUE TITLE
Automatically go to y 12 for /minebot tunnel branches?

### ISSUE THREAD

**Issue by LuisKleinwort** [michaelzangl/minebot#196]

**Comment by ghost** [comment]
Try /minebot walk
Or better /minebot pathfind

**Comment by LuisKleinwort** [comment]
This didn't work for me.

**Comment by ghost** [comment]
/minebot walk x y (Walking straight to the cords)
Or /minebot pathfind x y z (walking over obstacles)
What did not work?

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by michaelzangl** [comment]
… both of them don't dig, they just walk

**Comment by michaelzangl** [comment]
Pathfind now digs (when setting destructive mode), pathfind walks to that level even if it is far away (and can reach far destinations)
