### ISSUE TITLE
Fishing still broken (/minebot fish)

### ISSUE THREAD

**Issue by razorrider7** [michaelzangl/minebot#198]
Fishing for the 1.12 version doesn't seem to work, even in singleplayer. It just doesn't reel in the fish.

**Comment by EpiXSim0n** [comment]
Is already fixed but no new version is released yet.

**Comment by razorrider7** [comment]
Oh ok. When is he next release expected?

**Comment by michaelzangl** [comment]
I don't know when I will have time for it. Still needs some tweaking.

**Comment by Sopitive** [comment]
I have the same problem here. The bot will cast the rod, but will not reel it in. This feature also needs a delay between rod casts so the rod doesn't hit the entity before you pick it up or it goes into a hopper. Kinda like [this](http://www.liteloader.com/mod/autofish) mod that uses liteloader with forge. I know it may not be coded in the same way, but it is an example of what the mod should probably look like.

**Comment by michaelzangl** [comment]
Fixed fish bobble detection in 1.15
