### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Sizzlelgs** [michaelzangl/minebot#199]
Not a huge request, but instead of having to mark two locations (pos1 and pos2) perhaps something along the lines of /minebot clearcube 30

That would dig a 30 x 30 x 30 cube starting where you stand.

**Comment by michaelzangl** [comment]
This is what scripts are for. Store this in a new text file your `minebot/scripts` directory. Because every user wants something else (a flat area, fixed Y, ...)

```
/minebuild pos1 ~-30 ~-30 ~-30
/minebuild pos2 ~30 ~30 ~30
/minebuild clear
```

Then use `/minebot run filename.txt`. Tab complete is your friend
