### ISSUE TITLE
Lay rail not working?

### ISSUE THREAD

**Issue by Sizzlelgs** [michaelzangl/minebot#201]
![rail](https://user-images.githubusercontent.com/30684433/28995743-68c3ac4c-7a2c-11e7-8bf7-d52a4dcc4159.PNG)

From the minecraft forum page, there is no command...I tried various iterations but nothing worked...

Safe to assume since there was no command listed, it's not implemented yet?

**Comment by michaelzangl** [comment]
I think it is implemented, but one of those hidden features. Try `/minebot help`. All commands are listed there.

**Comment by Sizzlelgs** [comment]
Has his been updated for 1.13 or 1.14?

Thnkas
________________________________
