### ISSUE TITLE
Andesite, Diorite, and Granite

### ISSUE THREAD

**Issue by Sizzlelgs** [michaelzangl/minebot#202]
the command /minebot mine (insert block here) works on many items:  CoalOre, Iron_ore, Gold_ore, sand
Gravel, etc.

Can we get the ability to have it hunt for Andesite, Diorite, and Granite? Those sell fairly well on my server.

Thanks!

Sizz

**Comment by Hury999** [comment]
Can you give me IP of that server?

**Comment by michaelzangl** [comment]
Doesn't `stone:1` work any more?

**Comment by Sizzlelgs** [comment]
Thanks Michael, I will give that a try

edit - works! Thanks!
