### ISSUE TITLE
Minebot isn't working on 1.12 for me

### ISSUE THREAD

**Issue by biolibi** [michaelzangl/minebot#208]
Minebot isn't working for me on 1.12 forge doesn't detect it could you explain how I could use it?

**Comment by michaelzangl** [comment]
Could you explain how you tried it?

**Comment by biolibi** [comment]
I have download forge for 1.12 and put every file in AppData\Roaming\.minecraft\mods and when I launch minecraft it doesn't detect minebot

**Comment by ghost** [comment]
I think you did something wrong installing forge.
Try [THIS](http://m.wikihow.com/Install-Minecraft-Mods)


_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by biolibi** [comment]
[https://gyazo.com/6a7362bfc648709579b3cb9aac4464bc](url)
[https://gyazo.com/6a7362bfc648709579b3cb9aac4464bc](url)
Its working fine on other version but on 1.12 forge can't find the mod

**Comment by Sopitive** [comment]
Make sure it is not forge 1.12.1 it probably will not work with forge 1.12.1

**Comment by biolibi** [comment]
[https://gyazo.com/b9b1fa240c8ff951b5d9441abbde9d1f](url) doesn't work but what is mercurius_updater? Does that mean its should work but I have something wrong with my files?

**Comment by michaelzangl** [comment]
Supported version will only be 1.15 (once it is done)
