### ISSUE TITLE
/minebot feed not working with 1.12

### ISSUE THREAD

**Issue by gasag96** [michaelzangl/minebot#209]
It starts for a split second and instantly turns off without feeding anything.

**Comment by michaelzangl** [comment]
Are you standing next to cows/... and holding something to feed in your hand? Which animal/food did you try?

**Comment by gasag96** [comment]
Yes I'am. I tried it with Wheat an Seeds with Cows Pigs and Chickens. I used 1.12.1 and 1.12.2 (0.4) of your mod with forge 
1.12.1-14.22.1.2485 - Optifine 2. 

also tried with 
14.23.0.2503
14.22.1.2478
14.21.1.2443

**Comment by michaelzangl** [comment]
Feed gives better feedback on what is wrong in 1.15
