### ISSUE TITLE
Store Get Craft dont work on 1.12

### ISSUE THREAD

**Issue by ghost** [michaelzangl/minebot#216]
Craft gives an error everytime and all items used to craft just drop out. Store doesnt work at all.

**Comment by michaelzangl** [comment]
Do you have more details?
Especially: Which command did you use and for storing, which setup did you use (screenshot) - including the surrounding obstacles and the item frames.

**Comment by gsquaredxc** [comment]
@michealzangl
/minebot store
I personally had a chest underneath the player, then I tried underneath but one block away from the chest. I do not believe that this command works at all in 1.12.2, but I could be wrong.

**Comment by michaelzangl** [comment]
Craft is completely rewritten in 1.15, store should work there as well.
