### ISSUE TITLE
Minebot doesn't work

### ISSUE THREAD

**Issue by Frezzy123** [michaelzangl/minebot#223]
For some reason yesterday was working fine but today the bot doesn't work.
When i try /minebot mine it lags and then the bot shuts off
When i try /minebot lumberjack it says "Task timed out by 0.3 secs"
I tried reinstalling forge, not installing any mods (except minebot), reinstalling minebot, re-downloading both, and reinstalling minecraft and all.
I got it working 10 mins ago but then it says "Task timed out by 0.3 secs"
What's going on?

**Comment by michaelzangl** [comment]
Seems to be a starting position problem. Should be fixed in 1.15
