### ISSUE TITLE
Path finding not working

### ISSUE THREAD

**Issue by rtm516** [michaelzangl/minebot#229]
Running commands like `/minebot store` cause an error saying `Path finder did not find a path.`
Here is the stack trace, if anymore infomation is needed please dont hesitate to ask.
https://hastebin.com/jubuwoniqi

**Comment by michaelzangl** [comment]
The stack trace won't help much.

The error indicates that the bot cannot handle your layout. It has problems with things that are in the way, not enough space in front of the chests or it cannot handle your floor blocks,

Can you post a screenshot of your chests/layout, preferably also displaying the item frames?

**Comment by rtm516** [comment]
The world I tried it on was just a strip mine with the chest within 25 blocks of my player, I tried item frames on every side with no avail.

**Comment by michaelzangl** [comment]
Fixed in 1.15
