### ISSUE TITLE
1.12 wants 1.8, but 1.8 wants 1.12

### ISSUE THREAD

**Issue by Aaron2550** [michaelzangl/minebot#230]
When i run the latest pre-release in either forge 1.12.2 or 1.12, it says AimBow wants 1.8 but when i run it in 1.8 it says it wants 1.12...

Screenshot is german, just for showing you im not making shit up...

http://prntscr.com/j8k7ec

Maybe im just making a super small error ... but heres my log:

https://pastebin.com/QNKa6Z9X

**Comment by michaelzangl** [comment]
AimBow was not converted for the current MC version - but compiled against it. This is why it won't work with any of them. The mod is simply outdated.
