### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by iamalper** [michaelzangl/minebot#236]
[crash-2018-06-27_17.21.29-client.txt](https://github.com/michaelzangl/minebot/files/2142266/crash-2018-06-27_17.21.29-client.txt)

**Comment by michaelzangl** [comment]
You are using the wrong version of Minecraft and/or forge

**Comment by iamalper** [comment]
Thanks

27 Haz 2018 21:11 tarihinde Michael Zangl <notifications@github.com> yazdı:

You are using the wrong version of Minecraft and/or forge
