### ISSUE TITLE
1.7.10

### ISSUE THREAD

**Issue by longlostbro** [michaelzangl/minebot#238]
I'm assuming the latest version isn't compatible with 1.7.10
On some servers the version 0.2.4 works just fine but on some servers /minebot mine will say mining ores in the top right but it just spins around in circles. Are there specific known mods that minebot doesn't work well with?

Testing with my own standard FTB Infinity Evolved server it doesn't work but on another public server it does work.

**Comment by nightscloud2** [comment]
you need the latest version of minebot for 1.7.10. 0.2.4 is not it. you might be able to download a legacy build 0.3.0 from https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/wip-mods/2283099-minebot-0-3-released-can-now-store-in-chests-craft but it may not work in that version either, as the highest release for 1.7.10 is 1.0. (i think) so you need the highest build for 1.7.10.

**Comment by michaelzangl** [comment]
I uploaded all old releases: https://github.com/michaelzangl/minebot/releases
