### ISSUE TITLE
1.7.10

### ISSUE THREAD

**Issue by chidenmateusz** [michaelzangl/minebot#243]
Please create a version of this mod on forge 1.7.10
Many good mods and servers work on this version.

**Comment by nightscloud2** [comment]
I have a legacy version for 1.7.10 i can upload it for you. perhaps i will do that.

**Comment by AcidCult** [comment]
> I have a legacy version for 1.7.10 i can upload it for you. perhaps i will do that.

Can you upload 1.7.10 version for me?

**Comment by michaelzangl** [comment]
See #238

**Comment by AcidCult** [comment]
@michaelzangl There are links to downloads broken..
