### ISSUE TITLE
How can i send Chat Messages?

### ISSUE THREAD

**Issue by Finnlife** [michaelzangl/minebot#244]
I want to..

**Comment by nightscloud2** [comment]
there are several ways. which versions and methods do you use? you can use a build script with a loop, or you can use a javascript file with the API call to minescript.serverCommand(String)

**Comment by ascentfevers** [comment]
---------------------------------------------
Simple:
1.- Create a .txt file: every line of it should be one command / chat message.
2.- Save it in .minecraft\minebot\scripts
Example:
/minebuild mine diamond_ore
/minebot stop on fullinv
I am mining now.
/minebot pause 10
/minebot store
/back
---------------------------------------------
Funny, but what this script will do is mine diamonds, and stop when the inventory is full.
Then it will type a message in chat, stop 10 seconds, store the items, go back and repeat.
/minebot run "script.txt" will do the job.
