### ISSUE TITLE
Lag or freeze when reaching 100% Clear Area

### ISSUE THREAD

**Issue by NicciZar** [michaelzangl/minebot#247]
Whenever I clear an area or build an area the bot makes my Minecraft client freeze or run slow for a short period of time when reaching about 98 to 100% (two blocks at max for me) of the Clear Area

Im using Minecraft version 1.12.2

**Comment by michaelzangl** [comment]
When the area could be completely cleared (all is air/torches), this should not happen any more.

If not, you will still see this effect.
