### ISSUE TITLE
minebot 0.3

### ISSUE THREAD

**Issue by FrozenAtlas** [michaelzangl/minebot#252]
Would it be possible for you to rerelease the files from minebot 0.3? its the only minebot I've found that works with 1.7.10.

Found here: https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/wip-mods/2283099-minebot-0-3-released-can-now-store-in-chests-craft

**Comment by leopoldhub** [comment]
im searching too... if you found it call me plz...

**Comment by michaelzangl** [comment]
https://github.com/michaelzangl/minebot/releases
