### ISSUE TITLE
1.13.2 port

### ISSUE THREAD

**Issue by ghost** [michaelzangl/minebot#257]
Is there anyone who has a Port to 1.13.2?

**Comment by Juhcu** [comment]
I'm actually really interested in a port also, someone please respond thanks.

**Comment by turnip222** [comment]
heavily interested as well. will pay money for a port.

**Comment by Eyremba** [comment]
Please port AimBow too....

**Comment by ghost** [comment]
No one? Would pay for it...

**Comment by Tomoli75** [comment]
Yeah I really want this..

**Comment by Tomoli75** [comment]
???

**Comment by michaelzangl** [comment]
Closed - new target is 1.15.2
