### ISSUE TITLE
Minebuild can't pickup items from creative

### ISSUE THREAD

**Issue by Bielecki** [michaelzangl/minebot#26]
When I'm in creative mode, minebot keeps asking me for specific blocks instead pick them from creative. Right now I'm on MP server which allows me to store creative items only in hotbar, not in inventory and this asking every couple blocks is driving me mad.

**Comment by michaelzangl** [comment]
Thanks for your report. Minebot is not intended to be used in creative mode. All block break times/... are hardcoded for normal survival mode.
