### ISSUE TITLE
Mine faster

### ISSUE THREAD

**Issue by ascentfevers** [michaelzangl/minebot#264]
The bot works fine, but it can work faster. Is there any way to make it work faster?
I am using the "/minebuild clear" command which lets me clear a portion of stone.
But it is not as fast as if one did it by hand.
Is it possible to change any settings?
Is it even possible?

**Comment by michaelzangl** [comment]
Use /minebot clear <tab>. You will see different clear modes, try which one fits your pickaxe best.

**Comment by michaelzangl** [comment]
OK, github has issues with the formatting I used.
Type:
/minebot clear [TAB]
