### ISSUE TITLE
Durability

### ISSUE THREAD

**Issue by ascentfevers** [michaelzangl/minebot#267]
Not really an issue, but I don't know where to put it, sorry.
If I let the bot pick and the pickaxe is near to get broken, will the bot stop mining or change to another pickaxe in the hotbar?
Thanks in advance!

**Comment by xpr0legendx** [comment]
The bot will automatically switch to another pickaxe before your current one will break, if one is available that is. If there are no other pickaxes in your hotbar (or when all other pickaxes have no durability left before breaking), it will abort.

**Comment by michaelzangl** [comment]
Mind that this is true only for enchanted items. Normal pickaxes will just be broken, since repairing them makes no sense.
