### ISSUE TITLE
inv.getSlot(i).amount always returns 64

### ISSUE THREAD

**Issue by xpr0legendx** [michaelzangl/minebot#272]
Using this:
var inv = minescript.getInventory();
inv.getSlot(8).amount

will always return 64, even if there arent 64 items in that slot, or none at all.

.itemId does work, guess Ill simply have to check the id of that slot in order for me to check if I ran out of items or not.

**Comment by xpr0legendx** [comment]
nvm, had an error in my code

**Comment by Adam4HD** [comment]
Do you know how to get the type of item?

**Comment by xpr0legendx** [comment]
Yes, it's simple. Are you familiar with Java? If so you can look in the source of Minebot and see what your Javascript is supposed to look like. A minor change to the above code does what you want. If you wish to check if an item is in your inventory, simply loop through all slots
