### ISSUE TITLE
Some feedback on this code

### ISSUE THREAD

**Issue by VonHirsch** [michaelzangl/minebot#283]
Sorry, I know you didn't ask, but I feel compelled to give some feeback on this repo:

Pros:
- Free!  Thanks!
- Code compiles, runs and is compatible with 12.2.x
- Some commands like /minebot tunnel work out of the box

Cons:

- The code is not well commented
- The code is convoluted

Thanks for making this code public!  However due to its convoluted nature it is very difficult to patch, modify or customize.  Please don't take this personally, i've written plenty of spaghetti code myself :)

**Comment by michaelzangl** [comment]
Feel free to improve.
The problem with the bot are the many layers of abstraction, especially in the path finder. And the need to make it fast (really fast).

I'm closing this issue because it is too general. If you have any suggestions about specific parts of the code, feel free to open a new one.
