### ISSUE TITLE
1.15.2 Feature request: Can we get a mine mode to just do straight lines next?

### ISSUE THREAD

**Issue by bendauphinee** [michaelzangl/minebot#292]
The current /minebot mine command is very limited it seems. Can we get a minebot mineline or something like that which will just do a 2 high straight line next, instead of the crazy pathfind that mine does please?

**Comment by michaelzangl** [comment]
Are you using minebot on an Anti-Xray server? /minebot mine is using xray.

**Comment by bendauphinee** [comment]
Could not tell you the status of x-ray, but also, the mine pattern looks like a bot, where straight lines look... normal. Plus, it also likes to walk into caves if I leave it unattended for a minute, which makes me dead. Straight lines make this problem easier to deal with.

**Comment by michaelzangl** [comment]
Done in next beta: Enter those commands in this order:
```
/minebot stack begin
/minebot mine nearby
/minebot tunnel east branches torch_left
/minebot stack done
```
