### ISSUE TITLE
Target port to popular version: 1.8.9

### ISSUE THREAD

**Issue by pokabi11** [michaelzangl/minebot#293]
Hi there, i love your work. Your mod works perfectly. but...
1.8.9 is a version that almost people are waiting for, because most popular server are based 1.8.9. I cant recomplier your last version 1.8 it, so can you complier it?

**Comment by michaelzangl** [comment]
No. I will not be backporting features from 1.12 or 1.15 and will not be updating the very old 1.8 branch. Minecraft just changed too much between the versions
