### ISSUE TITLE
Need help on configuring /minebot clear command

### ISSUE THREAD

**Issue by zune127** [michaelzangl/minebot#296]
I'm not sure how to set up the command /minebot clear to setup specific areas, like a 13x13 area 9 blocks deep for instance. 

I remember on earlier minebot versions there was a /minebot pos1 and /minebot pos2 command, but it doesn't appear that command is in the 1.15 beta at the moment.

On the Wiki Get Started page, I see an example of the minebot clear command 
/minebot clear ~-2 ~ ~-2 ~2 ~-9 ~2 

For a 5x5 area 10 blocks deep, but I'm not sure how to configure the numbers used on the command to specify how many blocks in each direction, and how deep.

I can't find any additional information on how to properly use the /clear command beyond the aforementioned example posted in the Get Started page. 

Any help would be very much appreciated!

**Comment by michaelzangl** [comment]
Those are normal Minecraft coordinates.
https://minecraft.gamepedia.com/Commands#Tilde_and_caret_notation

/minebot clear ~-<Blocks to east> ~-<Blocks down> ~-<Blocks to south> ~<Blocks to west> ~<Blocks up> ~<Blocks to north>

This clears a 10 block to est, 20 block down, 30 block south, 40 blocks west, 50 blocks up and 60 blocks north area.
/minebot clear ~-10 ~-20 ~-30 ~40 ~50 ~60

You can also use absolute coordinates (get them using the F3): 
/minebot clear x1 y1 z1 x2 y2 z2

/minebuild pos1 / pos2 is not implemented yet, but will work in the future (use clear without coordinates)
