### ISSUE TITLE
What do I need to change to add sign reading feature for /minebot store 1.12.2

### ISSUE THREAD

**Issue by buten6** [michaelzangl/minebot#299]
1.12.2
the server I'm playing on does not let the player craft item frame.

or is there a way to use the latest version on 1.12.2 server?

**Comment by michaelzangl** [comment]
No. And I won't backport this feature. It would not be that difficult, but once I start backporting one thing, people will ask for the next...

Am 22. Juni 2020 12:17:42 MESZ schrieb buten6 <notifications@github.com>:

**Comment by buten6** [comment]
that's fair
If I change stuff in chestblockhandler.java will it work? 
sorry I am pretty new to this kind of stuff and I do not have any knowledge of coding and English isn't my first language 

if not it's fine then it's probably too hard for me to do anyway 
thanks for the quick reply!

**Comment by michaelzangl** [comment]
Signs implemented for 1.15 / 1.16 - just write the item id on it (e.g. coal_block)
