### ISSUE TITLE
/minebot craft 1 (item) not working in creative

### ISSUE THREAD

**Issue by ghost** [michaelzangl/minebot#30]
Whenever I try the command /minebot craft 1 (any item) the bot don't manage to craft the item. Sometimes the player even walks to the crafting table, but then an error message appears (an other strategy took over) or even the "invalid item move specification" appears when it tries to create a coal block.

**Comment by michaelzangl** [comment]
Hi. Which version of Minebot are you using? There is a known problem with many recipes (redstone_block, ...) but coal blocks should work. You need to have coal in your inventory.

The invalid item move seems to be a problem with your inventory management. Do you have any inventory mods installed?

**Comment by ferdal1** [comment]
I have the version v0.4b1 for minecraft 1.8, however the server I am using the bot has some type of inventory management plugin, maybe that's the problem?

**Comment by michaelzangl** [comment]
I'll reopen this for creative mode. There should at least be an understandable error message.

**Comment by ferdal1** [comment]
Well, what I tried to say is that it worked on survival/single player world whereas in the server I was playing it was not working. Not sure if it works on creative mode.

**Comment by michaelzangl** [comment]
Sorry, I misunderstood. It should work on any server.

**Comment by michaelzangl** [comment]
Issue is of old MC version - Minecraft has changed a lot since then.
