### ISSUE TITLE
Strategies involving block mining crash the game - 1.12.2

### ISSUE THREAD

**Issue by Clicky26** [michaelzangl/minebot#301]
Every time I attempt to start a minebot strategy that involves the mining of any block, the game crashes.

This error message was received after trying /minebot mine ender_chest :

`The game crashed whilst unexpected error
Error: java.lang.IllegalAccessError: tried to access field net.minecraft.item.ItemBlock.field_150939_a from class net.famzangl.minecraft.minebot.ai.task.inventory.ItemWithSubtype`

A clean install doesn't make a difference and loading it without other mods doesn't appear to make a difference either.

**Comment by michaelzangl** [comment]
Fixed in 1.15 / 1.16 - won't port fix to old versions
