### ISSUE TITLE
Farmbot suggestion

### ISSUE THREAD

**Issue by Erkko68** [michaelzangl/minebot#302]
The minebots are very good rn, but when I try to mine potatoes, sugar cane etc the bot start moving arrown the block without breaking it. I suggest to add a new command like /minebot farm (location) (location) (type of block). And optimize the movement to break corectly the plants. If the sugar cane only breaks the second layer to let grow infinitly it would be great. Good job.

**Comment by michaelzangl** [comment]
If this happens again, post a log of the bot (can be found on the console). This would be a bug.
