### ISSUE TITLE
Farming Bot 

### ISSUE THREAD

**Issue by jas1161** [michaelzangl/minebot#38]
It works very well and and as you have already marked for an update about the sugar cane breaking the second one, but I would find it very useful for it to have an option for it to do /sell all when the inventory has reached its capacity for a server with essentials

**Comment by michaelzangl** [comment]
Should the server command simply be issued when the inventory is full?

**Comment by jas1161** [comment]
Yes that is the concept

**Comment by michaelzangl** [comment]
Will be in the next release. See https://github.com/michaelzangl/minebot/wiki/Run#plant-and-sell on how to use.
