### ISSUE TITLE
Add chat commands support in API

### ISSUE THREAD

**Issue by TheTechPony** [michaelzangl/minebot#41]
I don't know how to suggest a feature so I suppose I'll put it here, I'd like for the ability to run a constant loop searching chat for a specific variable and then run a strategy based on that command.

This being included in the API, not the general /minebot commands. (Unless you want to)

**Comment by michaelzangl** [comment]
I added a method to access old chat messages.

Have a look at the [example](https://github.com/michaelzangl/minebot/wiki/Javascript-Examples#scanning-the-chat). Is this what you wanted?

There is also an example that stops when a given command was written (stopOnChatMessage).

**Comment by TheTechPony** [comment]
Yes, this will work very well. And do you have any extra documentation in scripting you can link me to? I'm new to Java and this is what's introducing me to the language.

**Comment by TheTechPony** [comment]
https://gyazo.com/9db76d4bf2192a23ca3e4a6f71c58f4b.png I get this error with this code copied off the documentation

minescript.doStrategy(minescript.stack(
        stopOnChatMessage(),
        minescript.strategy("minebot", "mine", "dirt")));

function stopOnChatMessage() {
    // This should work with the essentials /msg command
    // This matches messages sent from myUserName containing stop.
    // You can replace \u00a7 with § but make sure to change the encoding to UTF-8 in 
    // your text editor (should only be a problem for windows users)
    var re = /^\u00a76\[\u00a7c(myUserName)\u00a76 -> \u00a7c(me)\u00a76] \u00a7r.*stop.*$/;

    // Alternatives to this regexp:
    //   Match server shutting down:
    //      /^\u00a76.*shut.*down/
    //              ^ Replace this with the color code your server uses.
    //   Stop as soon as that person is mentioned (join message, ...)
    //      /supUserName/
    //   Stop as soon as the word test is in the message:
    //      /\btest\b/


    // we ignore old messages
    var messageCount = minescript.getChatMessages().length;
    // we should not just return false once, so we need to store the status.
    var stopReceived = false;
    return generateStopStrategy(function(h) {
            var messages = minescript.getChatMessages();
            // this goes through all new messages
            for (; messageCount < messages.length; messageCount++) {
                stopReceived |= re.test(messages[messageCount].textFormatted + "");
            }
            return stopReceived;
        }, false, "Stop when moving down.");
}

**Comment by michaelzangl** [comment]
You also need to copy the generateStopStrategy function a few lines above that example.

**Comment by TheTechPony** [comment]
Oh yeah I see, thanks a lot! :)
