### ISSUE TITLE
Auto fish

### ISSUE THREAD

**Issue by ghost** [michaelzangl/minebot#42]
Just encountered a bug while auto fishing with multiple accounts.

When auto-fishing with multiple accounts, if they are both in the same chunck, both accounts will retract their fishing rod. One of the accounts caught a fish and the other one didn't. Afther that they just continue as normal.

**Comment by michaelzangl** [comment]
This does not depend on the chunk. This hapens as soon as they are closer than 10m.

**Comment by michaelzangl** [comment]
This does not depend on the chunk. This hapens as soon as they are closer than 10m.

**Comment by michaelzangl** [comment]
Should be fixed in 1.15 version (checks coordinates)
