### ISSUE TITLE
Break ore with wrong pickaxe

### ISSUE THREAD

**Issue by walaoaaa1234** [michaelzangl/minebot#44]
v0.4b3

/minebot mine
/minebuild clear

Minebot break the iron ore with stone pickaxe but my hotbar has iron pickaxe

**Comment by michaelzangl** [comment]
That is intended, why should it use the iron pickaxe for that?


See the [Tools section of the wiki](https://github.com/michaelzangl/minebot/wiki/Tools) on how to change that, you will need:
```
  "iron&pickaxe": {
    "defaultValue": 1,
    "values": {
      "minecraft:iron_ore": 2
    }
  },
```
