### ISSUE TITLE
Chat message Error

### ISSUE THREAD

**Issue by EpiXSim0n** [michaelzangl/minebot#46]
I would need a little bit of help cause of this error:
JS Error: Type Error: "Insert any Chatmessage from Server" has no such function "matches" in <eval> at line numer 21
http://pastebin.com/ew5UL5Nx

**Comment by michaelzangl** [comment]
This is Javascript. use .match(...) ;-)
http://www.w3schools.com/jsref/jsref_match.asp

**Comment by EpiXSim0n** [comment]
Thanks it works =)
so in the wiki its wrong.
And another question is there any way to filter a word in the the chat so that i dont need the whole chatmessage to stop
I tried these but it didnt work:

function stopOnChatMessage() {
    var re = /.*test.*/;

So every time there a chat message with the word "test" in it the bot should stop working.

**Comment by michaelzangl** [comment]
Use the word boundary mark `\b`:
```javascript
/\btest\b/
```

**Comment by EpiXSim0n** [comment]
thanks but sorry it does not work can u give a look at it? normally it should stop when i am writing "test" in chat right? but it doesnt =(
http://pastebin.com/U5HHZsyD
Sry fpr my bad english :P

**Comment by michaelzangl** [comment]
Try using re.test(messages[messageCount].text + "")

It simply tests if that string contains a substring that matches.

**Comment by EpiXSim0n** [comment]
Something is wrong there xD
now it is typing the whole script in the chat and then it stops xD
![2016-01-06_17 18 02](https://cloud.githubusercontent.com/assets/16577384/12147493/802a663c-b499-11e5-81f5-d70ef940080c.png)

http://pastebin.com/FLYHAKUk

**Comment by michaelzangl** [comment]
Use /minebot js ... instead of /minebot run

**Comment by EpiXSim0n** [comment]
well.... yes. xD
thx it works now =)
