### ISSUE TITLE
Walking 

### ISSUE THREAD

**Issue by EpiXSim0n** [michaelzangl/minebot#47]
I have another question. After a chat message the bot should move x + 10 but i always get this error:
[Minebot] JS Error: null
But i cant find the issue =(
http://pastebin.com/vVE6fVeB

**Comment by michaelzangl** [comment]
You may not use that function there.

You should only return a boolean value. Simply add your walk towards at the end of the file.

**Comment by EpiXSim0n** [comment]
Thx worked :)
