### ISSUE TITLE
/minebot airbridge using 'WIDTH

### ISSUE THREAD

**Issue by iAmRinzler** [michaelzangl/minebot#48]
It seems that there is a bug using /minebot airbridge with the 'width' parameter.

Currently the function only works using SMALL (1 wide). The Function does work flawlessly with 1 wide airbridges.

changing the parameter to WIDE, WIDER, or MAXIMUM yields the "You must be standing on a half-slab" text.

EDIT: I figured it out. for /minebot airbridge WIDTH one needs to start the first row of blocks. I had been trying to do /minebot airbridge maximum while standing on a 1x1 area of slab. Thus for maximum width stand on a 1x7 platform of slabs placed on the lower half. The run /minebot airbridge maximum

Further EDIT: One needs to stand on the 'middle' block of the 1x7 platform or the bot throws the Stand on a half slab error. The bot needs to be able to see half slab on both sides of the player position to use the width parameter.

Note: Need to edit the helpText for airbridge.

**Comment by michaelzangl** [comment]
> Note: Need to edit the helpText for airbridge.

No, we need to write some help about that parameter. It is an undocumented feature. I also want to change the names to something more useful.

**Comment by iAmRinzler** [comment]
I updated my fork that addresses this issue. I did not change names since I feel like they only needed clarification. Pretty simple changes but makes the command much more clear. I spoke in my commit about a possible bug with using the length parameter though. Should we have length be distance traveled or blocks placed?

**Comment by michaelzangl** [comment]
Length should be distance traveled. So you can have a 2km long bridge and let the bot walk it while filling in blocks that were destroyed.
