### ISSUE TITLE
Facing

### ISSUE THREAD

**Issue by EpiXSim0n** [michaelzangl/minebot#50]
Is there any way to change the facing of the bot?
There is a option to walk
for example:
minescript.doStrategy(minescript.strategyWalkTowards(minescript.getPlayer().x + 0, minescript.getPlayer().z + 9));
but is there also a option to change the facing like

minescript.doStrategy(minescript.strategyFacingEast(minescript.getPlayer().f + 80, minescript.getPlayer().f + 9));
or .getLocation().getDirection()
or something else?

And is there an option to port away if an other player is nearby?

**Comment by michaelzangl** [comment]
(1) Do you want to change the facing while walking or only while standing? For standing, you can use /minebot look ...

(2)
https://github.com/michaelzangl/minebot/wiki/Javascript-Examples#search-for-entities
You can stop when a player is around. Then you can do whatever you want (issue server command, ...)

**Comment by EpiXSim0n** [comment]
the problem with /minebot look is that i only can change the facing like east or south but i cant change this:
![facing](https://cloud.githubusercontent.com/assets/16577384/12199248/0e3fd780-b617-11e5-907c-45d7fba26659.PNG)

**Comment by michaelzangl** [comment]
You need to tell the bot where to look:
/minebot look 100 64 100

**Comment by EpiXSim0n** [comment]
Is it possible that the wiki is wrong again?
Cause this won't work:
http://pastebin.com/Q2kYnrFp
Error:
![2016-01-08_23 05 17](https://cloud.githubusercontent.com/assets/16577384/12210784/cf87d2fe-b65c-11e5-809e-dc48a5d27fe6.png)

It should stop when a player is closer than 35 Blocks.

**Comment by michaelzangl** [comment]
No, the wiki is jus too up to date. I need to do a new release ;-)

**Comment by EpiXSim0n** [comment]
And when will u release the new release? :P

**Comment by michaelzangl** [comment]
Some time in the future. I have no specific release plan.

**Comment by EpiXSim0n** [comment]
So at the moment there is no way to walk/port away if a other player is nearby?

**Comment by michaelzangl** [comment]
No.
