### ISSUE TITLE
[Feature] Counting Mobs

### ISSUE THREAD

**Issue by Andi-fr** [michaelzangl/minebot#53]
Assume you have a cow farm next to a wheat farm.

It would be nice, if you could tell Minebot to kill all (adult) cows except e.g. 10 of them.

Using this you can send the bot harvesting, increasing the cows and finally killing some of them AND you will not run into the trouble of killing to much (killing all of them) or to less (freezing the server) cows.

**Comment by EdgarTx** [comment]
Check https://github.com/michaelzangl/minebot/wiki/Javascript-Examples#search-for-entities example. It clearly shows you how you can do this.

**Comment by Andi-fr** [comment]
Thank you very much. This is exactly what I was looking for.
