### ISSUE TITLE
Minebot follow?

### ISSUE THREAD

**Issue by TheTechPony** [michaelzangl/minebot#54]
You should add a minebot follow command to follow a certain player.

**Comment by michaelzangl** [comment]
What should happen then? The problem is that it is pretty complex to follow a player, what should we do if he jumps?

**Comment by TheTechPony** [comment]
Maybe every few seconds it gets the players location and then attempts the minebot walk strategy? Is there a function to grab the player's position already available? If so I can just use that to satisfy my need.

**Comment by michaelzangl** [comment]
Yes, you can do that. Simply use Javascript (untested)

```
function pause(time) {
  minescript.doStrategy(minescript.strategy(
          "minebot", "pause", (time * 1) + ""));
}

while(true) {
var es = minescript.getEntities("@p");
if (es.length > 0) {
minescript.doStrategy(minescript.strategyWalkTowards(es[0].x, es[0].z));
} else {
pause(1);
}
}
```

**Comment by TheTechPony** [comment]
One last question and then I'll be set to go, how can I select a specific player with the getEntites function?

**Comment by TheTechPony** [comment]
I didn't mean to close it. One last question before I'm finished, how can I select a specific player with the getEntities function?

**Comment by michaelzangl** [comment]
http://minecraft.gamepedia.com/Commands#Target_selectors

@p[name=...]

**Comment by TheTechPony** [comment]
Thanks a bunch! :)

**Comment by TheTechPony** [comment]
I feel like it'd be better for me to post in this than to open a new ticket, how could I go about pulling the name of the player that typed a command in the chat? Example someone said "follow" I can pull the name of that person and use it with @p

**Comment by TheTechPony** [comment]
Also this https://gyazo.com/40538af41dc18ff2aea6d06ff6820121.png

I'm sorry for asking so any questions, I have a friend helping me out but some things are specific to Minebot and he can't help me with those questions. Tell me if I become a trouble to you.

**Comment by TheTechPony** [comment]
Line 34
var es = minescript.getEntities("@p");

**Comment by michaelzangl** [comment]
You cannot really get the sender. Minecraft does not store that information as extra field and it depends on your server. But you can simply search for e.g. the first word in the chat line.

The exact format depends on your server, but something like:
```Javascript
var name = messages[messageCount].textFormatted.match(/(\w+):/)[1]
 var es = minescript.getEntities("@p[name=" + name + "\"");
```

Use an online regexp tool to verify your regexp.

**Comment by TheTechPony** [comment]
(/(\w+):/)[1]

Can you explain what exactly this is looking at or maybe use something from other examples? I assume the [1] is looking at the first word but I don't know what the rest is.

**Comment by TheTechPony** [comment]
I'm still getting an error even though I've set it up how you've shown.
https://gyazo.com/6f88a95b7ecc9fbbc16fb7aad28c88b1.png


var messageCount = minescript.getChatMessages().length;
var stopReceived = false;

    // This should work with the essentials /msg command
    // This matches messages sent from myUserName containing stop.
    // You can replace \u00a7 with § but make sure to change the encoding to UTF-8 in 
    // your text editor (should only be a problem for windows users)
    var re = /\bfollow\b/

    // Alternatives to this regexp:
    //   Match server shutting down:
    //      /^\u00a76.*shut.*down/
    //              ^ Replace this with the color code your server uses.
    //   Stop as soon as that person is mentioned (join message, ...)
    //      /supUserName/
    //   Stop as soon as the word test is in the message:
    //      /\btest\b/

while (true) {
    minescript.doNothing();
    var messages = minescript.getChatMessages();
    for (; messageCount < messages.length; messageCount++) {
        stopReceived |= re.test(messages[messageCount].textFormatted + "");
    }
	if (stopReceived) {
		minescript.serverCommand("Attempting to follow.");
		follow()
		var stopReceived = false;
	}
}

function follow() {
	var es = minescript.getEntities("@p[name=TheTechPony]");
	if (es.length > 0) {
		minescript.doStrategy(minescript.strategyWalkTowards(es[0].x, es[0].z));
	} else {
		pause(1);
	}
}

function pause(time) {
  minescript.doStrategy(minescript.strategy(
          "minebot", "pause", (time * 1) + ""));
}

**Comment by TheTechPony** [comment]
Got it working. Closed.
