### ISSUE TITLE
how do u get it to work with 1.8.9

### ISSUE THREAD

**Issue by jorge5882** [michaelzangl/minebot#55]
how do u get it to work with 1.8.9

**Comment by Andi-fr** [comment]
THIS QUESTION IS NO ISSUE CONCERNING THE MINEBOT SOFTWARE

Anyway these instructions may help you running the mod:
Use the Forge Mod Loader for Minecraft 1.8
Link: http://files.minecraftforge.net/

Getting the ModLoader:
1) Select Minecraft Version 1.8 (others are not tested by me) (open the link above)
2) Select the installer package (e.g. Win-Installer)
3) Download and follow the Instructions for installation
4) Now download the bundled Minebot archive file
5) Unzip the minebot.jar file from the archive to the forge mod directory

Finally start MC. Select the newly created forge profile and enjoy the mod.

**Comment by GoodDay360** [comment]
I custom-compiled the mod download it here:
https://www.mediafire.com/file/mtue06sr633oa3p/Minebot-custom-1.8.9.jar/file
