### ISSUE TITLE
Lumberjack - Not seeing stone pressure plate as safe side.

### ISSUE THREAD

**Issue by ratas897** [michaelzangl/minebot#6]
There has been an issue with the lumberjack wheare i have been playing in the minecraft prison server and the lumberjack leaves the lowest block of the tree and only cuts the rest leaving 1 block at every tree he cuts heres a picture of what he was doing http://puu.sh/h5ZAR/26f0c426ca.jpg why is he doing that ? is that because there are stone pressure plates beside the log?

**Comment by michaelzangl** [comment]
Yes, that is the reason. The bot does not know it, so it stays away from it.
