### ISSUE TITLE
Run server /eat command when hungry.

### ISSUE THREAD

**Issue by CarbonNeuron** [michaelzangl/minebot#60]
When Ever My Bot is mining its hunger bar will go down And if this is running on a server maybe add a way for the bot to send the chat command /eat if it has no food Or allow More customization for a basic user like me :D

**Comment by walaoaaa1234** [comment]
`/minebot mine `
This command will keep you feed when there is food in your hotbar.

If running on a server, use this to send chat command
`minescript.serverCommand("/home " + name);`
https://github.com/michaelzangl/minebot/wiki/Javascript-Examples#utility-functions

**Comment by CarbonNeuron** [comment]
How would I set the triggers for this tho?

**Comment by walaoaaa1234** [comment]
```javascript
minescript.doStrategy(minescript.stack(
          minescript.strategy("minebot", "eat"),
          minescript.strategy("minebot", "kill", "sheep", color, toKill + "")));
      }
```

Look around [Javascript Examples](https://github.com/michaelzangl/minebot/wiki/Javascript-Examples)

**Comment by CarbonNeuron** [comment]
What I was meaning to say would be when hunger gets low whail mining do the /eat command instead of finding food

**Comment by CarbonNeuron** [comment]
Bump

**Comment by dimasmi** [comment]
At the moment the bot eats immediatly if he gets 1/2 bar hungry. Is there a possibility to add distinguishing function which food he has to eat at the given hungry level

**Comment by michaelzangl** [comment]
@dimasmi Not at the moment.
Please open a new issue if you would want this.

**Comment by nightscloud2** [comment]
@CarbonNeuron Easy. make a text script like this. 

repeat:
stack:
/minebot stop after 300
/minebot mine
stack end
/eat

and if you have /fix, i'd put that under /eat. This will mine for 5 minutes then /eat then start mining again.
