### ISSUE TITLE
HardBlocks (Obsidian)

### ISSUE THREAD

**Issue by iAmRinzler** [michaelzangl/minebot#65]
I have noticed that the bot can't destroy obsidian.

Can't clear obsidian and can't /minebot mine obsidian.

**Comment by michaelzangl** [comment]
We can allow obsidian mining now that we have material based timeout computation. It should even work if you add it manually (/minebot settings edit)

**Comment by michaelzangl** [comment]
Just tested it, it works.

You need to:
```
/minebot settings edit
```
Find the "destructive" section
add Obsidian to footWalkThrough and headWalkThrough

The bot will then handle it like normal stone. Diamond + Efficiency pick is good to have ;-)

**Comment by ahoyaharr** [comment]
I hate to dig up an old thread, but when I try to use
`/minebot settings edit`
it throws that it is unable to find the settings file. 

Could you update your above answer to include the path to the files containing the relevant settings? Thanks!

**Comment by michaelzangl** [comment]
This should not happen. Is the file not found or simply the program for editing it?

Try `/minebot settings store` and see if the file is at the location you see in the chat.

**Comment by ahoyaharr** [comment]
That command generated a new subdirectory containing a .json which I have now editted. Thanks!! 

I don't know why the files were missing. I probably deleted it by mistake, but is it possible that Java didn't have write permissions during the first run?

**Comment by michaelzangl** [comment]
No, it seems that `/minebot settings edit` has some sort of error that `/minebot settings store` has not. I'll look into it.
