### ISSUE TITLE
Error when using minescript.getEntities("@p")

### ISSUE THREAD

**Issue by TheTechPony** [michaelzangl/minebot#67]
function follow() {
var es = minescript.getEntities("@p");
if (es.length > 0) {
minescript.doStrategy(minescript.strategyWalkTowards(es[0].x, es[0].z));
} else {
pause(1);
}
}

https://embed.gyazo.com/6f88a95b7ecc9fbbc16fb7aad28c88b1.png

**Comment by TheTechPony** [comment]
Line 33 is var es = minescript.getEntities("@p"); in my script

**Comment by michaelzangl** [comment]
Which version of Minebot are you using?

**Comment by TheTechPony** [comment]
Oh wow, I didn't even notice a new release. Solved and closed.
