### ISSUE TITLE
start

### ISSUE THREAD

**Issue by lory0101** [michaelzangl/minebot#69]
hello, I wanted to ask how do I open this program, really, even if I put it in the '' version '' should not be

**Comment by CarbonNeuron** [comment]
It is a mod

**Comment by CarbonNeuron** [comment]
You need to put aolimbow and minebot in your mods folder

**Comment by CarbonNeuron** [comment]
You need to put aimbow and minebot in your mods folder

**Comment by walaoaaa1234** [comment]
Download [FORGE](http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.8.html)
then put inside `.minecraft\mods\` folder

**Comment by michaelzangl** [comment]
Seems to be solved
