### ISSUE TITLE
Customizable preferences for the mining bot.

### ISSUE THREAD

**Issue by shadowraven92** [michaelzangl/minebot#70]
While I love the mining bot, I can’t get it to silk touch ores instead of using fortune on them.
I tried editing the minebot.json file tool editor but the bot still showed a clear preference for fortune instead of silk touch
I changed this in the tool rater section of the minebot.json
`"matches\u0026silk_touch": {
      "defaultValue": 1.0,
      "values": {
        "minecraft:monster_egg": 100.0
        "minecraft:coal_ore": 1
        "minecraft:diamond_ore": 2
        "minecraft:redstone_ore": 2
        "minecraft:emerald_ore": 2
        "minecraft:lapis_lazuli_ore": 2
        "minecraft:nether_quartz_ore": 2.5 } }`

And to use my normal effiency pick on stone I tried using
`"matches\u0026unbreaking": {
      "defaultValue": 1.01,
      "values": {
        "minecraft:stone": 5 } }` 

Any pointers on how to customize this?

Also p.s could you release a build c, I can’t build it seeing I do not run linux and I would very much enjoy having the new torch light setting option.

**Comment by michaelzangl** [comment]
That `\u0026` is a Java thing. Simply write &, it will also be recognized.

When writing json files, you need to add a `,` after each entry.

https://github.com/michaelzangl/minebot/wiki/Tools

The problem is that there is already a `silk_touch&matches` section. Scroll down, you should see dirt. Mind that a fortune-factor of 2 means you get a total rating of 8 for Fortune 3.

Simply change it:
```JSON
  "silk_touch&matches": {
    "defaultValue" : 1.0,
    "values": { 
      "minecraft:dirt" : [1, 1, 1.5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      "minecraft:diamond_ore": 10,
       "minecraft:emerald_ore": 10
    }
  }
```

I need some time to stabilize the bot, it currently has many unstable features (furnace, chest storing). I mean more unstable than usual ;-). The next build will be for MC 1.8.9

**Comment by shadowraven92** [comment]
Aah perfect!
One other question, now the bot seemingly randomly uses my silktouch pick or my work pick on stone.
This is probably because both my work pick and my silktouch pick have Effiency 4 and unbreaking 3. Making it just as likely for the toolrater to use.

Or it could be the stack script that I use to branchmine? At any rate..

It seems to revert to the last used pickaxe, so after it mined ore with the silktouch it'll proceed using that pickaxe. I thought about adding a new section to the toolrater like this.

` "efficiency\u0026matches": {
      "defaultValue": 1.0,
      "values": {
        "minecraft:stone": [ 3]
 } `

But that would still give it 'equal' value because my silktouch and workpick both have Effiency 4.
Is there a way for me to blacklist an ID in the silk_touch bit, or any other workaround I could use?

Also apologies for having to deal with a coding newb

**Comment by michaelzangl** [comment]
What do you want it to use on default?
Silk touch:
```JSON
  "silk_touch&matches": {
    "defaultValue" : 1.01,
    "values": { 
      "minecraft:dirt" : [1, 1, 1.5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      "minecraft:diamond_ore": 10,
       "minecraft:emerald_ore": 10
    }
  }
```

Non-silk touch:
```JSON
  "silk_touch&matches": {
    "defaultValue" : 0.99,
    "values": { 
      "minecraft:dirt" : [1, 1, 1.5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      "minecraft:diamond_ore": 10,
       "minecraft:emerald_ore": 10
    }
  }
```
