### ISSUE TITLE
Mining keeps timing out

### ISSUE THREAD

**Issue by badgercoder** [michaelzangl/minebot#71]
When I am using my script to mine, the mining bot keeps timing out when I am not in the game (I pressed 'u' to release the cursor). However, as soon as I click the game again, it starts working as normal. This only happens after the inventory is full, it does '/p h BadgerMc' then '/warp z' and tries to mine. What could be the cause of this?

https://youtu.be/MsfVtb2Os8s
# **mine.txt**

repeat:

/p h BadgerMc

/minebot walk -2382.5 -3054.5
/minebot walk -2403.1 -3054.5

/minebot walk -2403.1 -3056.5
/minebot walk -2403.1 -3058.5
/minebot js leftclick.txt
/minebot walk -2403.1 -3056.5

/minebot walk -2402.1 -3056.5
/minebot walk -2402.1 -3058.5
/minebot pause 1
/minebot js leftclick.txt
/minebot walk -2402.1 -3056.5

/minebot walk -2401.1 -3056.5
/minebot walk -2401.1 -3058.5
/minebot pause 1
/minebot js leftclick.txt
/minebot walk -2401.1 -3056.5

/minebot walk -2400.1 -3056.5
/minebot walk -2400.1 -3058.5
/minebot pause 1
/minebot js leftclick.txt
/minebot walk -2400.1 -3056.5

/minebot walk -2399.1 -3056.5
/minebot walk -2399.1 -3058.5
/minebot pause 1
/minebot js leftclick.txt
/minebot walk -2399.1 -3056.5

/warp z

/minebot walk -1456.5 502.5

stack:
/minebot stop on fullinv
/minebot stop after 300
/minebot mine
stack end <
# **leftclick.txt**

doLeftClick();

function doLeftClick() {
    function doLeftClickHandler(aiHelper) {
        aiHelper.overrideAttack();
    }
    minescript.doStrategy(generateRunOnceStarategy(doLeftClickHandler));
}

function generateRunOnceStarategy(runFunc) {
    var runFunc = runFunc;
    var RunOneTickStrategy = Java.type("net.famzangl.minecraft.minebot.ai.strategy.RunOneTickStrategy");
    var myRunOnce = Java.extend(RunOneTickStrategy, {
        singleRun: function(h) {
            runFunc(h);
        }
    });
    return new myRunOnce

**Comment by michaelzangl** [comment]
I also had this some times but it is hard to reproduce.

Changing the key binding code did not have any success so far (31e38b89a4d04c40b8b40b5d828cf340f1dfaad3), it seems to be something deep in minecraft code that makes minecraft assume that that button was released but the bot is still pressing it.

**Comment by beppe9000** [comment]
I also confirm this with a variation: minebot tries to mine a block but the key is not pressed enough, just like if it is resetted every tick. I'm using other mods tough, so it could be due to their presence.

However as long as the mouse is captured by the window the problem does not manifest: obviously this means I cannot leave the bot alone...

My script is simply a clearing operation with some teleports (the warp and the plot are in different dimensions, if it can help).

```
/minebuild pos1 1654 53 1285
/minebuild pos2 1632 35 1273

repeat:
#warp to mine
/warp PvpMine
/minebot pause 10

stack:
/minebot stop after 15
/minebot walk 1643.5 1279.5
stack end

stack:
/minebot stop after 300
/minebot stop on fullinv
/minebuild clear
stack end

/plot home
/minebot store
```

Also, I noticed that Zyin's HUD's coordinate text label disappears exactly when the timeouts start. So we have a way to detect the problem: the real work is to discover what causes the HUD to disappear and we will probably find the cause minebot times out.

**Comment by beppe9000** [comment]
was this fixed ?

**Comment by michaelzangl** [comment]
Probably. The 1.15 version changed how the focus is handled. If not, repoen (I'm just closing everthing that seems to not be reproducable on my side)

**Comment by beppe9000** [comment]
i don't even have minecraft installed these days... but I will reopen if i come across this again
