### ISSUE TITLE
About aimbow compatibility

### ISSUE THREAD

**Issue by CGsama** [michaelzangl/minebot#82]
Hi, 
I try to install the AimBow, but xaeros_minimap, EllianDetector, and RadarBro are not able to display.
![2016-02-28_13 27 14](https://cloud.githubusercontent.com/assets/15722562/13381054/8999a61a-de1f-11e5-9eef-c1d610cb497a.png)
![2016-02-28_13 30 13](https://cloud.githubusercontent.com/assets/15722562/13381053/899949fe-de1f-11e5-92f1-a1daa44eb40b.png)

**Comment by michaelzangl** [comment]
See #76

**Comment by CGsama** [comment]
I see, so might the problem of Forge
