### ISSUE TITLE
Use pathfinding with /minebot move

### ISSUE THREAD

**Issue by NotInfamy** [michaelzangl/minebot#88]
I've been testing this for a tiny bit so far, and it seems that the
`/minebot move <x> <y>`
doesn't use pathfinding?

The kill command will jump over blocks, so how would I make the move jump over blocks as it moves towards its destination?

**Comment by michaelzangl** [comment]
Please use /minebot pathfind x y z if you need pathfinding.

**Comment by NotInfamy** [comment]
There's no pathfind command at all though?

**Comment by michaelzangl** [comment]
There is. But this is only in the current git version and not in the latest release.

**Comment by NotInfamy** [comment]
Just built the current github version (gradle is amazing)
After running /minebot pathfind
It flashes with the strategy UI in the right, and then goes back to normal, no error message and nothing happens.
