### ISSUE TITLE
Another strategy took over - /minebot get

### ISSUE THREAD

**Issue by NotInfamy** [michaelzangl/minebot#89]
Just testing out the examples given within the wiki.
I have a chest in front of the bot (filled with carrots)
My inventory is completely empty

Javascript source:
```Javascript
var arr = [{slotIndex:0,amount:64,itemId:391,damageValue:-1}];
/*
for (var i = 1; i < 9; i++) {
  arr.push({slotIndex:i,amount:64,itemId:391,damageValue:-1});
}
*/
var strategy = minescript.strategy("minebot", "get", JSON.stringify(arr));
minescript.doStrategy(strategy);
```

Every time I try executing the script or the command itself it returns:

> [Minebot] Error: An other strategy took over.

I can see it flash up for the other strategies, but none of the other should kick in and stop it.

**Comment by michaelzangl** [comment]
Slot 0 needs to be empty. You need to have a chest in walkable distance. That chest needs an item frame attached to it. The item frame needs to display a carrot.

The bot should then walk to the chest and open it. If it does not work, try standing in front of the chest.
