### ISSUE TITLE
Can we get 1.9?

### ISSUE THREAD

**Issue by Ivcota** [michaelzangl/minebot#91]
Can we get an eta? Sry but this is such a good mod omg! XD

**Comment by CarbonNeuron** [comment]
Modding takes time

**Comment by CarbonNeuron** [comment]
And is hard to predict

**Comment by michaelzangl** [comment]
I won't be doing a 1.9 release this summer (or probably not even this year)

**Comment by Ivcota** [comment]
Ah man! Well thank you for the wonderful release for 1.8  :D

**Comment by MineWIZ** [comment]
I am actually porting current version to 1.7.10 then I will try port to 1.9.

**Comment by Ivcota** [comment]
Oh cool, thx MineWIZ!

**Comment by eileen12** [comment]
**1.10** is gonna release (**1st snapshot today !**) so it seems there _**will not be much of a need for 1.9**_.
