### ISSUE TITLE
How do I set an area of action?

### ISSUE THREAD

**Issue by beppe9000** [michaelzangl/minebot#92]
I am trying to automate a prison server. All the server is protected by world-guard except the mining zone. I would like to restrict the bot's actions to that area only.

**Comment by Linore** [comment]
You can define a cuboid by running the /minebuild pos1 and pos2
instructions.

**Comment by michaelzangl** [comment]
You cannot set an area for the mining command. You could use the clear command.

**Comment by beppe9000** [comment]
So, I did:
```
/minebuild pos1 235 63 -333
/minebuild pos2 240 60 -326
/minebuild clear
```
And the bot started clearing up that area.

**But now I wanted to alt-tab out of it but the bot stops if i do, and the log is flooded with text. If the window is focused again it continues.**

**Do you have any suggestion? I will try to disable the auto-pause.**

Are areas only supported in `/minebuild`? I think that supporting a defined area of action would be a really useful enhancement: for example prison server, plots, and factions territories.

**Comment by michaelzangl** [comment]
Try pressing `U` before changing windows.

**Comment by beppe9000** [comment]
Thanks, it worked!

**Comment by beppe9000** [comment]
Ps. How can I tell the bot to stop from /minebot mine after all tools are depleted?

**Comment by michaelzangl** [comment]
You need to script it yourself. You have full inventory acces from JS. The default stop methods only account for time or check if the inventory is full.
