### ISSUE TITLE
Better explaination of the settings file?

### ISSUE THREAD

**Issue by beppe9000** [michaelzangl/minebot#94]
How does the mining section of the `minebot.json` file works? What is the difference between `pointsMap`ad `factorMap`? I added the blocks i need to mine to both.

What is the `doubleBonus` value? Plus, can i make the bot stop if all tools are depleted?

I'm trying to make the bot use two picks: S (unbreaking III, silk & efficiency V) and R (unbreaking III & efficiency V) in order to reduce the space occupied by mining products.

I want to mine **only** the blocks in the following white-list following the given priority values.

| Block | Priority | Pick |
| --- | --- | --- |
| emerald_block | 3.77 | R |
| diamond_block | 3.24 | R |
| gold_block | 1.62 | R |
| emerald_ore | 1.10 | **S** |
| iron_block | 1.08 | R |
| diamond_ore | 0.9 | **S** |
| lapis_ore | 0.54 | **S** |
| coal_block | 0.545 | R |
| mossy_cobblestone | 0.30 | R |
| lapis_block | 0.27 | R |
| gold_ore | 0.18 | R |
| iron_ore | 0.12 | R |
| coal_ore | 0.06 | **S** |
| stone | 0.03 | **S** |
| cobblestone | 0.01 | R |

This is my current `toolRater`

```
"toolRater" : {
      "depleted" : {
         "defaultValue" : 0.0,
         "values" : {}
      },
        "diamond" : {
         "defaultValue" : 1.0,
         "values" : {
                         "minecraft:emerald_block" : 5,
            "minecraft:diamond_block" : 5,
            "minecraft:gold_block" : 5,
            "minecraft:emerald_ore" : 5,
            "minecraft:iron_block" : 5,
            "minecraft:diamond_ore" : 5,
            "minecraft:lapis_ore" : 5,
            "minecraft:coal_block" : 5,
            "minecraft:mossy_cobblestone" : 5,
            "minecraft:lapis_block" : 5,
            "minecraft:gold_ore" : 5,
            "minecraft:iron_ore" : 5,
            "minecraft:coal_ore" : 5,
            "minecraft:stone" : 5,
            "minecraft:cobblestone" : 5,
             "minecraft:dirt" : [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
         }
      },   
      "hand" : {
         "defaultValue" : 0.5,
         "values" : {}
      },

       "!silk_touch" : {
         "defaultValue" : 1,
         "values" : {
            "minecraft:emerald_block" : 5,
            "minecraft:diamond_block" : 5,
            "minecraft:gold_block" : 5,
            "minecraft:emerald_ore" : 0,
            "minecraft:iron_block" : 5,
            "minecraft:diamond_ore" : 0,
            "minecraft:lapis_ore" : 5,
            "minecraft:coal_block" : 5,
            "minecraft:mossy_cobblestone" : 5,
            "minecraft:lapis_block" : 5,
            "minecraft:gold_ore" : 5,
            "minecraft:iron_ore" : 5,
            "minecraft:coal_ore" : 0,
            "minecraft:stone" : 0,
            "minecraft:cobblestone" : 0
         }
      },
       "silk_touch_present": {
    "defaultValue" : 5.0,
    "values": { 
      "minecraft:dirt" : [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    }
  }
   }
```

Somehow this doesn't work properly: the bot uses the R pick on diamond ore and the block priority (see the table above) is messed up and it prefers to mine diamond ore than diamond block.

@michaelzangl I need some help understanding how all of this works... if I do I can contribute to the project wiki ;)

**Comment by michaelzangl** [comment]
How did you set the priority? The priority should work fine. It might be that the bot does not destroy diamond blocks, you need to whitelist it.

You told the bot that if ST was not present (`!silk_touch`) it should use the pick on diamond_ore. Remove the `!`.
