### ISSUE TITLE
Low performance with this configuration.

### ISSUE THREAD

**Issue by beppe9000** [michaelzangl/minebot#95]
I did a test with Minebot as the only mod installed so it is not a compatibility issue.
Minecraft becomes sluggish (0-7 fps) when `/minebot mine` is active.
I believe it is due to the configuration I am using and the amount of data that is processed in the game loop.
In order to properly track down the issue, here is my current configuration file: [minebot.json](https://github.com/michaelzangl/minebot/files/252162/minebot.json.txt)

**Comment by michaelzangl** [comment]
Is this only happening in this specific configuration or in any configuration you tried?

**Comment by beppe9000** [comment]
Pretty much with every configuration i tried. Clearing is also affected

**Comment by michaelzangl** [comment]
So this seems not to be related to the configuration.

Minebot pathfinding is pretty complex. You should have 2-4 CPU fast (3GHz+) cores for it.

**Comment by beppe9000** [comment]
![http://i.imgur.com/sEv5VV2.png](http://i.imgur.com/sEv5VV2.png)
Btw I noticed that it happens near the end of the work, for example at 98% 
 cleared so it probably is a problem in pathfinding for finding new blocks to mine?

**Comment by michaelzangl** [comment]
This is a known problem. The bot simply searches the whole area if it finds any missing blocks it could reach in any way - there are many possibilities and this makes the game lag a bit. It is a known "problem" but should not have any negative effects.

**Comment by beppe9000** [comment]
Are you doing that in the game thread?

**Comment by michaelzangl** [comment]
Yes

**Comment by beppe9000** [comment]
> Yes
That's a performance killer...

**Comment by michaelzangl** [comment]
Thanks, I know a bit about minecraft performance and performance killers. The bot is doing an extensive search with way more than 1 million possibilities to look at and rate. For that, it is doing a pretty good job ;-). The data structures to do pathfinding are about 10 times faster than plain minecraft ones because they are way more optimized (minecraft is so bad at this...) and use techniques like chunk lookup caching, bitmasks, bucket sorted lists, ...

**Comment by beppe9000** [comment]
Cool!

**Comment by michaelzangl** [comment]
@beppe9000 
I was hoping to port this to minecraft server - along with some other changes that solve the ticking entity problem without any of the spigot hacks that simply reduce the gaming experience.

This would make minecraft scale linear with the number of players. You could then run a 500 player server without problems (on a 4+ core machine). I send in some patches to spigot that improve locking and branch misprediction problems but they were not so interested.

**Comment by beppe9000** [comment]
Too bad for them... i t would be cool to have actual NPCs in multiplayer...
