### ISSUE TITLE
Using empty item frames as wildcards

### ISSUE THREAD

**Issue by beppe9000** [michaelzangl/minebot#96]
When I have my inventory filled by useless and not forecst things it would be cool to be able to dump them in a random chest to free inv space. So (unless some commands i missed lets me do that) i propose using chests with empty item frames as jolly chests that accept anything and can used to `/get` anything.

**Comment by michaelzangl** [comment]
I won't use empty item frames for this. Empty frames are often used to mark chests that should stay empty.
I was planning to add sign support some time ago, there you can specify a range of items.

**Comment by beppe9000** [comment]
What about using named items? like a dirt block named "EMPTY"

**Comment by michaelzangl** [comment]
I'll think about it. I currently do not have the time to implement it. Feel free to try, the chest scanning mechanism is not that complex (there is a simple item-matches-chest method)

**Comment by nightscloud2** [comment]
Sign support would be amazing considering most of the servers i play on have item frames disabled because it can be used to dupe items. Signs would be great.

**Comment by beppe9000** [comment]
> I'll think about it. I currently do not have the time to implement it. Feel free to try, the chest scanning mechanism is not that complex (there is a simple item-matches-chest method)

I will have a look...

> Sign support would be amazing considering most of the servers i play on have item frames disabled because it can be used to dupe items. Signs would be great.

Some servers don't like bots. Signs are suspicious... For example  consider one (hypothetical bad format) that reads:

> MINEBOT
> STORE
> 264

If i was an admin i would investigate the user for sure if i found lots of chests with this format.

I propose the usage of a sign format that is easily disguised as a chest shop sign:

> Beppe9000
> 264
> S4784
> Air

The first row is the username of the user, required by most chest shop plugins.
The second row is the block id for diamonds disguised as the number of item sold.
The  third row is the item price. We could use this value for more options like 1 means `STORE ONLY` or 1 `GET ONLY` or 3 `STORE ANY` or 4 `STORE+ACCEPT NAMED`. 
The last row is an item that is not available in the server (user defined) so that the shop is never used as a shop.

A note on this idea: on many servers if a shop is created you can only open the chest by right-clicking the shop sign, so this might need some attention.

**Comment by michaelzangl** [comment]
I would simply write the item to be placed in the chest on the sign.

Supported values would be: "stone", "minecraft:stone", "1". For Ranges: "1..4". And a "*" for any item, a "**" to only drop items. We do not need a special format - every sign on a chest that has valid item names on it is considered to be a drop/take sign.

**Comment by beppe9000** [comment]
I was thinking... if we make a chest that accepts everything the bot would store armor and tools too...
Some kind of white-list is needed in this case.

**Comment by ghost** [comment]
Hey, is the sign support already done?
Many people need it beacause come servers disable item frames
I dont mind If the sign has a suspicious name.
