### ISSUE TITLE
Command to wait for chat message matching regex expression

### ISSUE THREAD

**Issue by beppe9000** [michaelzangl/minebot#98]
Another feature that deserves to be added is the ability to wait for a chat message during a script, instead of estimating the wait using the pause command.

For example, given the following chat sequence:

```
/login uberpassword
[CHAT] You are now logged in
/server prison
[CHAT] Welcome to prison
/p h
```

I use this script to login

```
/login uberpassword
/minebot pause 1
/server prison
/minebot pause 5
/p h
```

If the `/minebot waitchat` command was added the above script could be changed to:

```
/login uberpassword
/minebot waitchat ^You are now logged in
/server prison
/minebot waitchat ^Welcome to prison
/p h
```

Notice how it is improved as now it is more flexible regarding the server taking too much time to do things.

**Comment by Linore** [comment]
You can call functions from the JS API to do what you are trying to do.
Directly from the documentation:

minescript.getChatMessages(): ChatMessage[]
> Gets an array of all chat messages received since the client was started.
> This also includes chat messages from previous games.
> New messages are appended, so you can simply remember the length of this
> array to filter for new messages.


https://github.com/michaelzangl/minebot/wiki/Javascript-API#minescriptgetchatmessages-chatmessage

That being said, you should chill out when it comes to opening new issues.
Read the documentation, do some experimentation, and then if you really
can't make any progress then it might be time to open a ticket.

[image: Inline image 1]
^ This is way too much, especially considering that the author has decided
to take a break from this project.

**Comment by beppe9000** [comment]
I knew about the JS API, but I did think that exposing such a function as a command would make it easier when doing plain text scripts.

Regarding chilling out it, is hard to figure things when many are poorly documented, however I can assure you I usually try hard enough before asking. In this case I am simply suggesting a feature.

PS: Do you know if there any other mods like this?

**Comment by michaelzangl** [comment]
https://github.com/michaelzangl/minebot/wiki/Javascript-Examples#custom-stop-condition

You can also just wait until ... happens.

The JS API is really menat for this.
