### ISSUE TITLE
/minebuild pos1 x y z kills scripts

### ISSUE THREAD

**Issue by nightscloud2** [michaelzangl/minebot#99]
Create a text script and put /minebuild pos1 [x y z] any lines after this command do not execute. 
I realized this issue after trying to do this script 

/minebuild pos1 0 1 0
/minebuild pos2 0 2 0

The second command doesn't run. No commands will run after the first /minebuild pos1 command. 
I've also tried doing this in a javascript file like this 

var x = minescript.getPlayer().x;
var y = minescript.getPlayer().y;
var z = minescript.getPlayer().z;
minescript.serverCommand("/minebuild pos1 " + x + " " + y + " " +z);
minescript.serverCommand("/minebuild pos2 " + x+10 + " " + y-1 + " " +z);
minescript.serverCommand("/minebuild clear");

But no command will run after minescript.serverCommand("/minebuild pos1 " + x + " " + y + " " +z);
its as if that command kills the script. 
I even made 2 different javascript files 1 for setting the pos1 and another for setting a pos2 and put them in a text script like this

/minebot js C://setPos1.js
/minebot js  C://setPos2.js

The first js script runs, but the 
The /minebuild pos1 command just kills anything after it. When that command is typed, all the scripts die as if it did a /minebot stop 

Test it yourself. If anyone can get the bot to set pos1 to its current pos and then set pos2 10 blocks in front, and 1 block down on the y, that would be great. @michaelzangl

**Comment by michaelzangl** [comment]
Do you have linux? If yes, download the current master branch and compile it yourself. The error should be fixed there.

**Comment by nightscloud2** [comment]
@michaelzangl I'm sure i could figure it out, but I haven't done it before. Is their anyway you can publish a new release for me? I can donate to you for your time if you have paypal. I really need that fix and im not sure how to compile it myself.

**Comment by beppe9000** [comment]
### How to build (you need linux)
1. Download the master branch: https://github.com/michaelzangl/minebot/archive/master.zip
2. Extract it somewhere
3. Double-click the `release.sh` file
4. Both mods (minebot and the aimbot extension) are in the `releases` folder, inside a folder named after the version tag (currently `e3b501e`)

### How to build with windows
1. Download the master branch: https://github.com/michaelzangl/minebot/archive/master.zip
2. Extract it somewhere
3. Go to the subfolder of the mod you want to compile (`Minebot` in this case), open a command prompt by shift-right-clicking an empty space inside that directory
4. type `gradlew build` and press enter
5. the compiled mod is in the `build\libs` sub-directory
